name: Build and Package - Windows

on: [push, pull_request, workflow_dispatch]
# on: [workflow_dispatch]

jobs:
  # build-hnsd:
  #   runs-on: windows-latest

  #   defaults:
  #     run:
  #       shell: msys2 {0}

  #   steps:
  #     - name: Setup mysys2 and install dependencies
  #       uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: MINGW64
  #         path-type: inherit
  #         update: true
  #         install: git mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-unbound autotools

  #     - name: Set git autocrlf
  #       run: git config --global core.autocrlf input
  #       shell: bash

  #     - name: Checkout hnsd repository
  #       uses: actions/checkout@v4
  #       with:
  #         repository: 'handshake-org/hnsd'
  #         ref: master

  #     - name: Build hnsd
  #       run: |
  #         ./autogen.sh && ./configure && make
  #         ls -l

  #     - name: Store hnsd binary
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: hnsd-bin
  #         path: ./hnsd.exe
  #         if-no-files-found: error

  build-fingertip:
    # needs: build-hnsd
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Build fingertip
        # $env:GOBIN = "/mingw64/bin";
        env:
          GOBIN: /mingw64/bin
        run: |
          env
          go get github.com/akavel/rsrc
          rsrc -arch amd64 -ico ./builds/windows/fingertip.ico -manifest builds/windows/manifest.xml -o ./rsrc.syso
          go build -trimpath -o ./builds/windows/ -ldflags "-H windowsgui"
          dir
          dir builds/windows

      - name: Download hnsd binary
        uses: actions/download-artifact@v4
        with:
          name: hnsd-bin
          path: builds/windows
      
      - name: Package as msi
        working-directory: ./builds/windows
        run: |
          go-msi make --msi fingertip.msi --version 0.0.1 --src templates --arch amd64
          dir

      - name: Store fingertip binary
        uses: actions/upload-artifact@v4
        with:
          name: fingertip-bin
          path: ./builds/windows/fingertip.exe
          if-no-files-found: error

      - name: Store fingertip installer
        uses: actions/upload-artifact@v4
        with:
          name: fingertip-msi
          path: ./builds/windows/*.msi
          if-no-files-found: error
